server.port=${SERVER_PORT:8080}
spring.application.name=urlshortener

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false

spring.flyway.enabled=true

app.base-url=${APP_BASE_URL}
